### PR TITLE
modify consumer and producer configure

### PR DESCRIPTION
**Pull request by nmred**

### CODE REVIEW

**Comment by lcobucci** [comment]
@nmred please halt this effort. We shouldn't add any dependency injection lib as dependency, the library should enable dependency injection not give a container to users.

**Comment by nmred** [comment]
@lcobucci you mean , We should implement injection lib?

**Comment by lcobucci** [comment]
> @lcobucci you mean , We should implement injection lib?

@nmred not at all, we need simply to ensure that ALL classes are compliant with the OOD principles. That would enable dependency injection, which is our goal. Providing a basic setup for a DI container is usually out of scope of libraries (we usually do these things in modules/bundles/*).

It's better (and easier) to do that from the internal classes first because they hardly have any dependency. That's why I've asked you to stop working on this, otherwise we would end up adding too much unnecessary complexity to the lib.

**Comment by nmred** [comment]
@lcobucci 
At present, the main modify points are as follows:

1. All classes can dependency injection to facilitate testing
2. Split the configuration class so that it can be configured flexibly
3. Modify single class by using dependency injection
4. Encapsulation `Amp\Loop` class，centralized management watcher，ensure can cancel all `Amp\Loop` watcher at stop

Temporary use lib `php-di`, follow up can implement the dependency injection container，direct replacement is all right，I not understand why you want to stop developing this ?

Can you give an example of a dependency injection?

You say don't use di lib, and think 

> providing a basic setup for a DI container is usually out of scope of librarie

, So how do we call this lib if we can change it to dependency injection? can you provide me a pseudo code?

**Comment by lcobucci** [comment]
> Temporary use lib php-di, follow up can implement the dependency injection container，direct replacement is all right，I not understand why you want to stop developing this ?

@nmred the problem with this implementation is that when starting from the outer layer you get into anti-patterns, like injecting the container in a internal class. We're already doing this in this PR (which is getting bigger and quite difficult to review properly) in the `Broker` class, that's why I suggested to stop this, design things, and then implement things better.

We need to review the whole way we manage connections and clusters, and that's exactly what I'm working now (just need to first fix one thing in the produce message which is not being compatible with Kafka Streams API 1.0+).

> , So how do we call this lib if we can change it to dependency injection? can you provide me a pseudo code?

The only places we need to combine all the objects are the integration tests and examples, and we should simply create the objects by ourselves, like:

```php
interface A
{}

final class B implements A
{}

final class C
{
    private $a;

    public function __construct(A $a)
    {
        $this->a = $a;
    }

    public function doSomething(): void
    {}
}


$c = new C(new B());
$c->doSomething();
```

**Comment by nmred** [comment]
> We need to review the whole way we manage connections and clusters, and that's exactly what I'm working now (just need to first fix one thing in the produce message which is not being compatible with Kafka Streams API 1.0+).

Originally planned, we first rebuilt the dependency injection, perfect the unit test, and finally add Kafka Streams API 1.0+ of the support.

**Comment by nmred** [comment]
@lcobucci  I agree  stop this PR, but we should create a milestone for v0.3 release

**Comment by lcobucci** [comment]
> Originally planned, we first rebuilt the dependency injection, perfect the unit test, and finally add Kafka Streams API 1.0+ of the support.

@nmred the thing is that the project I'm working on at the moment will use the Kafka Streams (in Java) so I do need to produce messages compatible with 1.0+ 😄 

> @lcobucci I agree stop this PR, but we should create a milestone for v0.3 release

Alright, I'm wrapping up some stuff regarding other libraries and then I'll send a PR with the work I've done regarding the brokers refactoring 👍

**Comment by nmred** [comment]
@lcobucci 
> @nmred the thing is that the project I'm working on at the moment will use the Kafka Streams (in Java) so I do need to produce messages compatible with 1.0+ 😄

I know Java  Kafka Stream , I mean this project only implement  kafka 0.10.x  protocol, kafka 0.11 and 1.0 protocol need implement

**Comment by lcobucci** [comment]
@nmred I get this msg when I try to stream messages produced by `kafka-php`:

```
has invalid (negative) timestamp. Possibly because a pre-0.10 producer client was used to write this record to Kafka without embedding a timestamp, or because the input topic was created before upgrading the Kafka cluster to 0.10+.
```

So it does look like a 0.10+ compatibility issue, I'm fixing this already so don't worry

**Pull request closed without merging**
