### PR TITLE
singleton

### PR DESCRIPTION
**Pull request by simPod**
Based on this https://github.com/weiboad/kafka-php/issues/177 I tried to remove singleton config from this lib so each consumer doesn't rely on that single instance.

I have created symfony bundle that I'm pushing soon and I tested it there

### CODE REVIEW

**Comment by lcobucci** [comment]
@simPod this won't really work because the broker is also a singleton, then you start getting into the work I'm doing....

**Comment by lcobucci** [comment]
Also, we have functional tests that covers the basic features of the library, so we don't need that SF bundle

**Comment by simPod** [comment]
I implemented that bundle for my case in different repo.

I see that broker now. That's more work than I though then

**Comment by lcobucci** [comment]
> I implemented that bundle for my case in different repo.

@simPod right, sorry

> I see that broker now. That's more work than I though then

waaaaay more, unfortunately

**Comment by lcobucci** [comment]
But we're not THAAAT far, though.

That's the main reason why the functional test suite got added, be able to break everything and ensure that the basic stuff work

**Comment by lcobucci** [comment]
@simPod should we close the PR then?

**Comment by simPod** [comment]
Yup. I think you have better chance solving this

**Pull request closed without merging**
