### PR TITLE
verify https://github.com/weiboad/kafka-php/issues/179

### PR DESCRIPTION
**Pull request by noname007**
TDD may be good! but not the only thing in the world!!!!!!!

### CODE REVIEW

**Comment by lcobucci** [comment]
> TDD may be good! but not the only thing in the world!!!!!!!

Considering the fact the test is being added after the code was done, this is not really TDD, right? However adding tests to the test suite is **the only way** to enforce that nasty bugs like this will ever happen again.

**Comment by lcobucci** [comment]
@noname007 can you please address the issues pointed by Travis?

**Comment by noname007** [comment]
i was trying.....

**Comment by lcobucci** [comment]
@noname007 can I help you with anything?

**Comment by noname007** [comment]
i agree you point above.but don't agree the point only just use the test to prove the problem exsits.

**Comment by noname007** [comment]
@lcobucci yes , i wonder why my test was skipped?

**Comment by noname007** [comment]
i found this was skipped ,because missing env variables 
`Environment variables "KAFKA_VERSION", "KAFKA_TOPIC", and "KAFKA_BROKERS" must be provided` 

how i pass this to the test case?

**Comment by noname007** [comment]
https://travis-ci.org/weiboad/kafka-php/jobs/335624593

**Comment by lcobucci** [comment]
@noname007 if you look at the build stages in travis you'll see that the functional test suite was not executed because the previous stage failed. If you fix that it will execute your test in the functional test stage.

**Comment by noname007** [comment]
#189

**Comment by noname007** [comment]
@lcobucci i need your help to complete this test scripts for implement the desc in #188 #189

**Pull request closed without merging**
