### PR TITLE
Implement compression properly

### PR DESCRIPTION
**Pull request by lcobucci**
This PR fixes the creation and parsing of compressed message sets, making the library work follow the [Kafka protocol](https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol-Messagesets) regarding that functionality.

@nmred some other small fixes are included I can extract them to a different PR to make it easier to review. I really recommend you to review this commit by commit

### CODE REVIEW

**Comment by nmred** [comment]
> some other small fixes are included I can extract them to a different PR to make it easier to review.

Good method, I will use this method in the future 👍

**Comment by lcobucci** [comment]
> Good method, I will use this method in the future 👍

@nmred I try to have atomic commits and atomic PRs as much as possible. `git rebase` and `git add -p` are great tools to help on that =)

**Comment by Im0rtality** [comment]
@nmred @lcobucci  https://github.com/weiboad/kafka-php/pull/163/files#diff-3e73c513e41712529b1b24d133cbe487R134 original message offset is getting set to zero after decompression. This bubbles to Assignment::consumerOffsets, gets commited and then fetched. Result of this, you constantly keep reprocessing same batch of message starting from offset=0 over and over again. 

This makes lib unusable with compressed messages. Could you check this behaviour?

As workaround I have passed `$ret['data']['offset']` into recursive call and then writing into decompressed message.

**Comment by lcobucci** [comment]
@Im0rtality that's quite unexpected, specially considering that the integration test suite passes... could you try to reproduce that behaviour in a test? You can use https://github.com/weiboad/kafka-php/blob/master/tests/Functional/Ticket/GH181Test.php as example

**Comment by Im0rtality** [comment]
I can't provide test suite due to time constraints, however after quick glance over existing tests I could not see case where offset passed from broker is being checked after decompression. There's only validation of offsets from decompressed message (messageSet?) that are autoincrementing from zero. That specific zero is cause of issue.

**Comment by lcobucci** [comment]
@Im0rtality the functional test suite produces (using "sync" and "async" modes) and consumes messages with and without compression (checking the exact number of consumed messages). So, in theory, if the assignment of offsets was incorrect it wouldn't be possible to consume things properly (but it's definitely possible that the tests are not 100% correct).

**Pull request merged**
